### ISSUE TITLE
k8s 检测一直提示 operator 无效，实际已经安装

### ISSUE THREAD

**Issue by alvin5840** [chaitin/HummerRisk#394]
**HummerRisk 版本**
v1.0.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**严重程度（高、中、低）**
高

**Bug 描述**
提示 tirvy operator 没有安装，实际已经安装。
<img width="896" alt="image" src="https://user-images.githubusercontent.com/107904113/232454265-24f9f377-c46e-4781-a6c8-5160321603f9.png">

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/107904113/232453991-7c782a9a-c404-4f84-b4de-6c42536a2b96.png">

**Bug 重现步骤(有截图更好)**
1. 添加装了 trivy operator 的k8s集群

**Comment by harris1943** [comment]
校验报错还是按照报错
