### ISSUE TITLE
v1.0.0 相关建议

### ISSUE THREAD

**Issue by toadzhou** [chaitin/HummerRisk#402]
**HummerRisk 版本**
版本:   v1.0.0

**你希望我们怎样改进？**
1、云资源检测结果，看起来有点混乱，对于检测结果显示方式的原因容易早曾统计混乱。作为用户只关心我哪些实例不合规，如何改进，改进意见，是否屏蔽等等。
2、检测和资源实例区别应该分开，大部分的区别是没有资源实力的，每次检测都要并发的都所有区域进行扫描，完了反回无资源。
资源实例同步一天一次，或手动强制同步一下就行了，完了按有资源的地区去进行扫描。
3、站内消息内容，如果只是通知那就把超链拿掉。现在是有超链，但点了无任何反应。
4、规则检测组创建无任何反应，之前的版本是可以创建的。我们的需求是自己创建规则组，把需要的规则加到入自己定的规则组内，完了自己再添加一些内置规则组以外的规则。但目前这个版本来看有点麻烦。
5、云资源拓扑图 要么就拿掉，要么就要体现他的价值，目前我个人是有点看不懂的。加了反而是个扣分项
**你的思路建议是什么？**
1、以实例为单位展示，或者规则展示的话使用体验上再琢磨琢磨。具体的我也答不上来，我只知道好不好用。
2、创建云账号的时候或者创建完云账号后可以很方便的修改针对的区别，只要一个区域修改编辑的选项，而不需要为每个规则制定区域选择选项。
3、要么就是通知一下就行了，要么链接到消息的详细页面。
4、可能是bug或者我这块的哪里问题，但目前来看应该是代码的问题。
5、短期可以拿掉，要么换好一些的图数据库展现。

还有一些，到嘴边忘记了，等想起来再来补充吧。

**Comment by harris1943** [comment]
v1.1.0相关需求
