### ISSUE TITLE
云原生检测中，在资源态势通过 namespace 过滤出来的资源不对

### ISSUE THREAD

**Issue by harold5384** [chaitin/HummerRisk#431]
**HummerRisk 版本**
v1.2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**严重程度（高、中、低）**
低

**Bug 描述**
资源态势通过 namespace 过滤出来的资源不对，例如：default 的 namespace 是有资源的
<img width="747" alt="image" src="https://github.com/HummerRisk/HummerRisk/assets/117808901/c0f61cb5-56f6-4db8-8af6-4d94e9db177b">

<img width="1264" alt="image" src="https://github.com/HummerRisk/HummerRisk/assets/117808901/60e5c827-dfec-4462-b23f-13a15dc1b2fc">

**Bug 重现步骤(有截图更好)**
*

**Comment by harris1943** [comment]
您这边试试重新新建一个同步任务，将资源重新同步一下再看看。
<img width="1512" alt="image" src="https://github.com/HummerRisk/HummerRisk/assets/105598469/496dfbc8-ffd6-44d4-84ea-f28793540de9">

**Comment by harris1943** [comment]
好的，感谢您的反馈，我们会尽快处理

**Comment by harris1943** [comment]
已完成
